language: php

php:
    - 7.1
    - 7.0
    - 5.6

addons:
    apt:
        sources:
            - elasticsearch-2.x
        packages:
            - elasticsearch

services:
    - elasticsearch

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - composer self-update
    - composer validate

install:
    - composer update --prefer-dist
    - tests/Application/bin/console doctrine:schema:create --env=test -vvv --no-interaction
    - tests/Application/bin/console fos:elastica:reset --env=test -vvv --no-interaction

script:
    - bin/phpspec run --no-interaction
    - bin/phpunit
    - bin/behat --strict -vvv --no-interaction
